name: For Production

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container Image
        run: |
          DOCKER_BUILDKIT=1 \
          docker build . \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}" \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}" \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" \
            --cache-from vsrecorder/webapp:${{ github.ref_name }} \
            --tag vsrecorder/webapp:${{ github.ref_name }}
      - name: Push Container Image
        run: |
          docker push vsrecorder/webapp:${{ github.ref_name }}

  notify-slack:
    if: ${{ always() }}
    needs:
      - build-and-push-container-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Slack Notification
        run: |
          SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}" \
          SUCCESS="${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && !contains(needs.*.result, 'skipped') }}" \
          WORKFLOW="${{ github.workflow }}" \
          SERVER_URL="${{ github.server_url }}" \
          REPOSITORY="${{ github.repository }}" \
          BRANCH="${{ github.ref_name }}" \
          SHA="${{ github.sha }}" \
          RUN_ID="${{ github.run_id }}" \
          ACTOR="${{ github.actor }}" \
          /bin/bash ./.github/scripts/notify_slack.sh
